var message = "hello";
alert(message);
message = "Goodbye";
alert(message);
message = "she's a great person";
alert(message);
var htmlSnippet = '<h1 class="special">Important Headline</h1>';
var message = 'she\'s a great person';
alert(message);
htmlSnippet = "<h1 class=\"special\">Important Headline</h1>";
document.write(htmlSnippet);
htmlSnippet = "&lth1 class=\"special\"&gtImportant Headline&lt/h1&gt";
document.write(htmlSnippet);
